[job]
dump_folder = "./outputs"
description = "Qwen2.5 VL 7B training"

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 10
enable_wandb = true

[model]
name = "Qwen/Qwen2.5-VL-7B-Instruct"
flavor = "7B"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm

[optimizer]
name = "AdamW"
lr = 5e-5

[training]
batch_size = 2
seq_len = 32768 # 131072 # maximum sequence length for this model
warmup_steps = 10  # lr scheduler warm up # warmup_ratio 0.03
max_norm = 1.0  # grad norm clipping
steps = 100000 # around 5 epochs
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 8
compile = false
dataset = "alfred"

[experimental]
context_parallel_degree = 1
pipeline_parallel_degree = 2

[checkpoint]
enable_checkpoint = false
folder = "checkpoint"
interval_type = "steps"
interval = 5000
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'selective'  # ['none', 'selective', 'full']
selective_ac_option = 'op'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_float8_linear = false
